apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: app-arealogada
  labels:
    strimzi.io/cluster: llkafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Topics and groups used by the HTTP clients through the HTTP Bridge
      # Change to match the topics used by your HTTP clients
      - resource:
          type: topic
          name: src-arealogada-user-json
        operation: Read
      - resource:
          type: topic
          name: src-arealogada-user-json
        operation: Describe
      - resource:
          type: topic
          name: src-arealogada-user-json
        operation: Write
      - resource:
          type: topic
          name: src-arealogada-user-json
        operation: Create
