apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: src-arealogada-user-json
  labels:
    strimzi.io/cluster: llkafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    min.insync.replicas: 3
